# Generated by Django 3.0.14 on 2024-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.CharField(max_length=64, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
